name: Feature Request
description: 새로운 기능 추가
title: "[Feature]: "
body:
  - type: textarea
    attributes:
      label: 📝 개요
      description: 해당 이슈에 대한 설명을 작성해 주세요.
      placeholder: Assignees, Labels, Projects 체크
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🎯 해야 할 일
      description: 해야 하는 작업 내용을 작성해 주세요.
      placeholder: |
        - [ ] task1
        - [ ] task2
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🔗 참조
      description: 이슈와 관련된 링크를 남겨주세요.
      placeholder: https://dpdpwl.tistory.com/16
    validations:
      required: true